{
    "name": "KillCounter",
    "version": "1.0.0",
    "api": [
        "3.14.0"
     ],
     "mcpe-protocol": [
        "361",
        "388",
        "389",
        "390",
        "407",
        "408"
     ],
    "author": "BlockHorizons",
    "authors": [
        "Sandertv (@Sandertv)",
        "Luke (@lukeeey)"
    ],
    "main": "BlockHorizons\\KillCounter\\Loader",

    "permissions": {
        "killcounter": {
            "default": false,
            "description": "Allows access to every feature of KillCounter",
            "children": {
                "killcounter.command": {
                    "default": false,
                    "description": "Allows access to all KillCounter commands",
                    "children": {
                        "killcounter.command.killstats": {
                            "default": true,
                            "description": "Allows access to the killstats command"
                        },
                        "killcounter.command.killstop": {
                            "default": true,
                            "description": "Allows access to the killstop command"
                        }
                    }
                }
            }
        }
    }
}
