---
name: "KillCounter"
version: 1.0.0
api: [2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
author: "BlockHorizons"
main: BlockHorizons\KillCounter\Loader

permissions:
  killcounter:
    default: false
    description: "Allows access to every feature of KillCounter"
    children:
      killcounter.command:
        default: false
        description: "Allows access to all KillCounter commands"
        children:
          killcounter.command.killstats:
            default: true
            description: "Allows access to the killstats command"
          killcounter.command.killstop:
            default: true
            description: "Allows access to the killstop command"
...